[phases.setup]
aptPkgs = ["libcairo2", "libcairo2-dev", "libpango-1.0-0", "libgdk-pixbuf2.0-0", "libffi-dev", "shared-mime-info"]

[phases.install]
cmds = ["pip install -r requirements.txt"]

[start]
cmd = "bash start.sh"
