[build]
builder = "nixpacks"

[deploy]
startCommand = "bash start.sh"
healthcheckTimeout = 300
restartPolicyType = "never"

[env]
PYTHONUNBUFFERED = "1"
DEBIAN_FRONTEND = "noninteractive"
NIXPACKS_PYTHON_VERSION = "3.11"
