[build]
builder = "nixpacks"

[deploy]
startCommand = "bash start.sh"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "never"

[env]
PYTHONUNBUFFERED = "1"
DEBIAN_FRONTEND = "noninteractive"
